name: OpenVINO - Basic Test

on:
  workflow_dispatch:
  schedule:
    - cron: "41 1 * * *" # run every day at 1:41
  push:
    branches:
      - v*-release
  pull_request:
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule') ||  (github.event_name == 'push') || contains( github.event.pull_request.labels.*.name, 'openvino-test') }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]
        os: ["ubuntu-22.04", "windows-latest"]
        include:
          - python-version: "3.12"
            os: "ubuntu-22.04"
            transformers-version: "4.36.0"
          - python-version: "3.12"
            os: "ubuntu-22.04"
            nncf: "git+https://github.com/openvinotoolkit/nncf.git"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install PyTorch CPU to prevent unnecessary downloading/installing of CUDA packages
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install openvino nncf
          pip install .[tests]
      - if: ${{ matrix.transformers-version }}
        run: pip install transformers==${{ matrix.transformers-version }}

      - name: Pip freeze
        run: pip freeze

      - name: Basic tests
        run: |
          pytest tests/openvino/test_modeling_basic.py

      - if: ${{ matrix.nncf }}
        run: pip install ${{ matrix.nncf }}

      - name: Slow tests
        run: |
          pytest tests/openvino -s -m "run_slow" --durations=0
        env:
          RUN_SLOW: 1
